name: TKT-CYBER-XMD
services:
  - name: tkt-cyber_xmd-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
